version: "3.8"

services:
  php:
    build: .
    volumes:
      - .:/var/www/symfony
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/symfony:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8910:80"
    depends_on:
      - php
    networks:
      - symfony

networks:
  symfony:
